### model
model_name_or_path: ./qwen25vl_7b_Instruct

### method
stage: sft
do_train: true
finetuning_type: full
freeze_vision_tower: true
freeze_multi_modal_projector: true
freeze_language_model: false
deepspeed: examples/deepspeed/ds_z3_config.json

### dataset
dataset: pebr_r1_warm_up
dataset_dir: ./dataset/sft
template: qwen2_vl
cutoff_len: 4096
overwrite_cache: true
preprocessing_num_workers: 128
dataloader_num_workers: 4

### output
output_dir: saves/qwen2_5vl-7b/full/pebr_r1_warm_up
logging_steps: 10
save_steps: 5000000
plot_loss: true
overwrite_output_dir: true
save_only_model: true
report_to: wandb  # choices: [none, wandb, tensorboard, swanlab, mlflow]

### train
per_device_train_batch_size: 4
gradient_accumulation_steps: 4
learning_rate: 1.0e-5
num_train_epochs: 2
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000
resume_from_checkpoint: null

### eval
# val_size: 0.1
# per_device_eval_batch_size: 1
# eval_strategy: steps
# eval_steps: 500
